# Chapter 1 Vectors, Matrices, and Arrays

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

import numpy as np
from scipy import sparse

## 1.1 Creating a Vector

In [2]:
# create a vector as a row
vector_row = np.array([1, 2, 3])

# create a vector as a column
vector_column = np.array([[1],
                          [2],
                          [3]])
vector_row
vector_column

array([1, 2, 3])

array([[1],
       [2],
       [3]])

## 1.2 Creating a Matrix

In [3]:
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

## 1.3 Creating a Sparce Matrix

In [4]:
matrix = np.array([[0, 0], 
                   [0, 1], 
                   [3, 0]])
matrix_sparse = sparse.csr_matrix(matrix)

matrix
print(matrix_sparse)

array([[0, 0],
       [0, 1],
       [3, 0]])

  (1, 1)	1
  (2, 0)	3


## 1.4 Selecting Elements

In [5]:
vector = np.array([1, 2, 3, 4, 5, 6])
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
vector[2]
matrix[1, 1]
vector[:]
vector[3:]
vector[:3]
vector[-1]
matrix[:2, :]
matrix[:, 1:2]

3

5

array([1, 2, 3, 4, 5, 6])

array([4, 5, 6])

array([1, 2, 3])

6

array([[1, 2, 3],
       [4, 5, 6]])

array([[2],
       [5],
       [8]])

## 1.5 Describing a Matrix

In [6]:
matrix = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
matrix.shape
matrix.size
matrix.ndim

(3, 4)

12

2

## 1.6 Applying Operations to Elements 

In [7]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
add_100 = lambda i: i + 100
# create a vectorized function
vectorized_add_100 = np.vectorize(add_100)
# apply function to all elements in matrix
vectorized_add_100(matrix)
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

## 1.7 Finding the Maximum and Minimum Values

In [8]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
np.max(matrix)
np.min(matrix)
np.max(matrix, axis = 0)
np.max(matrix, axis = 1)

9

1

array([7, 8, 9])

array([3, 6, 9])

## 1.8 Calculating the Average, Variance, and Standard Deviation

In [9]:
np.mean(matrix)
np.var(matrix)
np.std(matrix)
np.mean(matrix)

5.0

6.666666666666667

2.581988897471611

5.0

## 1.9 Reshape Arrays

In [10]:
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])
matrix.reshape(2, 6)
# one row and as many columns as needed
matrix.reshape(1, -1) # 2D
matrix.reshape(matrix.size) # 1D

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## 1.10 Transposing a Vector on Matrix

In [11]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# transpose matrix
matrix.T
# transpose vector
np.array([1, 2, 3, 4, 5, 6]).T # failure
np.array([[1, 2, 3, 4, 5, 6]]).T #success

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

array([1, 2, 3, 4, 5, 6])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## 1.11 Flattening a Matrix

In [12]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix.flatten()
# matrix.reshape(1, -1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## 1.12 Finding the Rank of a Matrix

In [13]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
np.linalg.matrix_rank(matrix)

2

## 1.13 Calculating the Determinant

In [14]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]], dtype=np.float)
np.linalg.det(matrix)

-9.51619735392994e-16

## 1.14 Getting the Diagonal of a Matrix

In [15]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# return diagonal one above the main diagonal
matrix.diagonal(offset=1)
# return the main diagonal
matrix.diagonal()
# return diagonal one below the main diagonal
matrix.diagonal(offset=-1)

array([2, 6])

array([1, 5, 9])

array([4, 8])

## 1.15 Calculating the Trace of a Matrix

In [16]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# np.sum(matrix.diagonal())
matrix.trace()

15

## 1.16 Finding Eigenvalue and Eigenvector

In [17]:
matrix = np.array([[1, -1, 3],
                   [1, 1, 6],
                   [3, 8, 9]])
eigenvalue, eigenvectors = np.linalg.eig(matrix)
eigenvalue
eigenvectors

array([13.55075847,  0.74003145, -3.29078992])

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

## 1.17 Calculating Dot Products

In [18]:
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
np.dot(vector_a, vector_b)
vector_a @ vector_b

32

32

## 1.18 Adding and Substracting Matrices 

In [19]:
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])
np.add(matrix_a, matrix_b)
np.subtract(matrix_a, matrix_b)
matrix_a + matrix_b
matrix_a - matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

## 1.19 Multiplying Matrices 

In [20]:
matrix_a = np.array([[1, 1],
                     [1, 2]])
matrix_b = np.array([[1, 3],
                     [1, 2]])
# matrix multiplication
np.dot(matrix_a, matrix_b)
matrix_a @ matrix_b
# hadamar product
matrix_a * matrix_b

array([[2, 5],
       [3, 7]])

array([[2, 5],
       [3, 7]])

array([[1, 3],
       [1, 4]])

## 1.20 Inverting a Matrix

In [21]:
matrix = np.array([[1, 4],
                   [2, 5]])
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

## 1.21 Denerating Random Values

In [22]:
np.random.seed(0)
# generate 3 floats (0, 1)
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])