# Chapter 1
**Introduction to PyTorch, Tensors, and Tensor Operations**

PyTorch is the most optimized high-performance tensor libaray for computation of deep learning tasks on GPUs and CPUs.

In [1]:
import torch
print(torch.version.__version__)
import numpy as np

1.9.0


## Recipe 1-1 Using Tensors Problem
Problem: The data structure used in PyTorch is graph based and tensor based, therefore, it is important to understand basic operations and defining tensors.

In [2]:
x = [12, 23, 34, 45, 56, 67, 78]

In [3]:
# Check whether an object is a tensor
torch.is_tensor(x)

False

In [4]:
# Checks whether the object is stored as tensor object
torch.is_storage(x)

False

In [5]:
y = torch.randn(1, 2, 3, 4, 5)

In [6]:
torch.is_tensor(y)

True

In [7]:
torch.is_storage(y)

False

In [8]:
# total number of elements in the input Tensor
torch.numel(y)

120

In [9]:
torch.eye(3, 4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [10]:
torch.eye(5, 4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])

In [11]:
x1 = np.array(x)
x1

array([12, 23, 34, 45, 56, 67, 78])

In [12]:
# create tensor from numpy array
torch.from_numpy(x1)

tensor([12, 23, 34, 45, 56, 67, 78], dtype=torch.int32)

In [13]:
torch.linspace(0, 10, 6)

tensor([ 0.,  2.,  4.,  6.,  8., 10.])

In [14]:
torch.logspace(0, 5, 6)

tensor([1.0000e+00, 1.0000e+01, 1.0000e+02, 1.0000e+03, 1.0000e+04, 1.0000e+05])

In [15]:
# uniform distribution
torch.rand(5)

tensor([0.6884, 0.9997, 0.4533, 0.3848, 0.8632])

In [16]:
# normal distribution
torch.randn(5)

tensor([-0.2242, -0.2139,  1.2971, -0.6188,  0.1633])

In [17]:
# random permutation
torch.randperm(10)

tensor([2, 8, 1, 6, 5, 0, 7, 4, 3, 9])

In [18]:
# range
torch.arange(0, 6, 2)

tensor([0, 2, 4])

In [19]:
d = torch.randn(4, 5)
d

tensor([[ 1.4988,  0.7820,  1.1093, -0.7197,  2.2248],
        [ 0.8712,  0.8407, -0.4717,  0.8201,  1.1824],
        [-0.4169,  0.6827, -1.5203,  0.8765, -0.5428],
        [-1.7168, -0.5058,  0.9082, -1.0186, -1.0988]])

In [20]:
torch.argmax(d, dim=1)

tensor([4, 4, 3, 2])

In [21]:
torch.argmin(d)

tensor(15)

In [22]:
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# concatenate along the rows
torch.cat((d, d), axis=0)

tensor([[ 1.4988,  0.7820,  1.1093, -0.7197,  2.2248],
        [ 0.8712,  0.8407, -0.4717,  0.8201,  1.1824],
        [-0.4169,  0.6827, -1.5203,  0.8765, -0.5428],
        [-1.7168, -0.5058,  0.9082, -1.0186, -1.0988],
        [ 1.4988,  0.7820,  1.1093, -0.7197,  2.2248],
        [ 0.8712,  0.8407, -0.4717,  0.8201,  1.1824],
        [-0.4169,  0.6827, -1.5203,  0.8765, -0.5428],
        [-1.7168, -0.5058,  0.9082, -1.0186, -1.0988]])

In [24]:
# concatenate along the cols
torch.cat((d, d), axis=1)

tensor([[ 1.4988,  0.7820,  1.1093, -0.7197,  2.2248,  1.4988,  0.7820,  1.1093,
         -0.7197,  2.2248],
        [ 0.8712,  0.8407, -0.4717,  0.8201,  1.1824,  0.8712,  0.8407, -0.4717,
          0.8201,  1.1824],
        [-0.4169,  0.6827, -1.5203,  0.8765, -0.5428, -0.4169,  0.6827, -1.5203,
          0.8765, -0.5428],
        [-1.7168, -0.5058,  0.9082, -1.0186, -1.0988, -1.7168, -0.5058,  0.9082,
         -1.0186, -1.0988]])

In [25]:
# split the tensor along the row
torch.chunk(d, 2, axis=0)

(tensor([[ 1.4988,  0.7820,  1.1093, -0.7197,  2.2248],
         [ 0.8712,  0.8407, -0.4717,  0.8201,  1.1824]]),
 tensor([[-0.4169,  0.6827, -1.5203,  0.8765, -0.5428],
         [-1.7168, -0.5058,  0.9082, -1.0186, -1.0988]]))

In [26]:
# split the tensor along the row
torch.chunk(d, 2, axis=1)

(tensor([[ 1.4988,  0.7820,  1.1093],
         [ 0.8712,  0.8407, -0.4717],
         [-0.4169,  0.6827, -1.5203],
         [-1.7168, -0.5058,  0.9082]]),
 tensor([[-0.7197,  2.2248],
         [ 0.8201,  1.1824],
         [ 0.8765, -0.5428],
         [-1.0186, -1.0988]]))

In [27]:
# split the 1D tensor into chunks
torch.split(torch.arange(8), 3)

(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7]))

In [28]:
# gather function
# selected tensor, dim, index tensor
torch.gather(torch.tensor([[1, 2], [3, 4]]), 1,
             torch.tensor([[0, 0], [1, 0]]))

tensor([[1, 1],
        [4, 3]])

In [29]:
a = torch.randn(4, 4)
indices = torch.tensor([0, 2])
print(a)
# along the row
print(torch.index_select(a, 0, indices))
# along the column
print(torch.index_select(a, 1, indices))

tensor([[-1.1874, -0.3550, -0.9898, -0.6189],
        [ 1.1864,  1.1604,  0.4877,  0.4427],
        [ 2.7553, -0.2464, -0.0495,  0.9362],
        [-0.1548, -0.1142,  0.4113, -0.6319]])
tensor([[-1.1874, -0.3550, -0.9898, -0.6189],
        [ 2.7553, -0.2464, -0.0495,  0.9362]])
tensor([[-1.1874, -0.9898],
        [ 1.1864,  0.4877],
        [ 2.7553, -0.0495],
        [-0.1548,  0.4113]])


In [30]:
# return the index of nonzero elements in tensor
torch.nonzero(torch.tensor([10, 20, 30, 0, 0.0]))

tensor([[0],
        [1],
        [2]])

In [31]:
x = torch.randn(5, 4)
# transpose for 2D tensor
x.t()

tensor([[ 0.9033, -0.1929, -0.7468, -0.3164, -0.8901],
        [ 0.4914, -0.6321, -0.5446,  0.3563,  0.3636],
        [-0.3728, -0.3397, -2.3241,  1.8920, -1.1631],
        [-2.3113,  1.6245,  0.7958, -1.1334, -0.4528]])

In [32]:
# transpose along these two axis
# for ndim tensor
# x.transpose(a, b) == x.transpose(b, a)
x.transpose(0, 1)

tensor([[ 0.9033, -0.1929, -0.7468, -0.3164, -0.8901],
        [ 0.4914, -0.6321, -0.5446,  0.3563,  0.3636],
        [-0.3728, -0.3397, -2.3241,  1.8920, -1.1631],
        [-2.3113,  1.6245,  0.7958, -1.1334, -0.4528]])

In [33]:
# remove row index
torch.unbind(x, 0)

(tensor([ 0.9033,  0.4914, -0.3728, -2.3113]),
 tensor([-0.1929, -0.6321, -0.3397,  1.6245]),
 tensor([-0.7468, -0.5446, -2.3241,  0.7958]),
 tensor([-0.3164,  0.3563,  1.8920, -1.1334]),
 tensor([-0.8901,  0.3636, -1.1631, -0.4528]))

In [34]:
# remove col index
torch.unbind(x, 1)

(tensor([ 0.9033, -0.1929, -0.7468, -0.3164, -0.8901]),
 tensor([ 0.4914, -0.6321, -0.5446,  0.3563,  0.3636]),
 tensor([-0.3728, -0.3397, -2.3241,  1.8920, -1.1631]),
 tensor([-2.3113,  1.6245,  0.7958, -1.1334, -0.4528]))

In [35]:
# math functions
x = torch.randn(2, 3)
print(x)
print(torch.add(x, 10))
print(torch.mul(x, 10))
print(torch.ceil(x))
print(torch.floor(x))
print(torch.clamp(x, min=-0.5, max=0.5))
print(torch.exp(x))
# the fraction part of the element
print(torch.frac(x))
# log(x + 1)
print(torch.log1p(x))

tensor([[-0.3296,  1.0179,  0.7032],
        [ 1.7873,  0.4935, -1.9258]])
tensor([[ 9.6704, 11.0179, 10.7032],
        [11.7873, 10.4935,  8.0742]])
tensor([[ -3.2956,  10.1789,   7.0315],
        [ 17.8727,   4.9352, -19.2578]])
tensor([[-0.,  2.,  1.],
        [ 2.,  1., -1.]])
tensor([[-1.,  1.,  0.],
        [ 1.,  0., -2.]])
tensor([[-0.3296,  0.5000,  0.5000],
        [ 0.5000,  0.4935, -0.5000]])
tensor([[0.7192, 2.7673, 2.0201],
        [5.9731, 1.6381, 0.1458]])
tensor([[-0.3296,  0.0179,  0.7032],
        [ 0.7873,  0.4935, -0.9258]])
tensor([[-0.3998,  0.7021,  0.5325],
        [ 1.0251,  0.4011,     nan]])
